### ISSUE TITLE
All players are getting kicked when Vanilla-Kick Function is executed

### ISSUE THREAD

**Issue by moelrobi** [galaxy119/EXILED#75]
Title.
The Issue lays probably, that every player on my server has the same ip.

**This is for us mandatory!**

When a kick is issued the console throws `HandleData Unknown connectionId:1
(Filename: ./Runtime/Export/Debug/Debug.bindings.h Line: 35)`

**Comment by galaxy119** [comment]
That message is highly unhelpful since it's related to keybindings which aren't actually used by the server anyways.

As for the issue, I suggest you resolve the "all players have the same IP" issue, as this is something wrong with your server configuration, and not EXILED, this is not something we can help with.
